### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-popper#102]
I haven't been able to help maintain this project as much as I would like. Is there anyone that would like to start to help maintain this library? You would be in charge of pretty much everything, reviewing issues, PRs, publishing, etc. I could step in and answer questions if needed, just been swamped with other projects lately.

**Comment by FezVrasta** [comment]
Obviously count me in to help, but if possible I'd like someone else to maintain the library and continue to give support as I did so far.

If nobody adopts the project I can take it.

**Comment by fantua** [comment]
For now seems good idea to add permissions for @FezVrasta to release #93 and publish fix. It's highest priority.

Also you can continue looking for another maintainer.

**Comment by supergibbs** [comment]
@Justkant @pzatrick are also active contributors

**Comment by souporserious** [comment]
@FezVrasta I gave you access to the repo as well as the NPM package. Please let me know if you need anything else and also feel free to add more contributors if anyone is willing to help. I'll try and help out with whatever I can when work slows down.

**Comment by Justkant** [comment]
Hi, I can help too but it's a first for me.
