### ISSUE TITLE
Allow different tags for Target

### ISSUE THREAD

**Issue by tgreen7** [souporserious/react-popper#107]
I am trying to have a Popover in an svg, but it seems like the Target element is always rendered as a ```<div>```. This is making my Popovers not show up in svg elements.

**Comment by souporserious** [comment]
You can use the `component` prop to change the rendered DOM node of `Target`. Please see in the [docs here](https://github.com/souporserious/react-popper#component-proptypesoneoftypeproptypesnode-proptypesfunc), as well as an example of using a custom component [here](https://github.com/souporserious/react-popper/blob/master/example/animated.jsx#L119).

**Comment by tgreen7** [comment]
Awesome thanks!
