### ISSUE TITLE
Standalone examples not working -  Uncaught TypeError: Cannot read property 'getTargetNode' of undefined

### ISSUE THREAD

**Issue by saurishkar** [souporserious/react-popper#110]
### Steps to reproduce the problem

1.  Open https://react-popper-example-fies9l.stackblitz.io/
2.  Click on any of the standalone examples.
3.  Check the browser console.

### What is the expected behavior?

It should have probably worked as a normal popup example.

### What went wrong?

1. Uncaught TypeError: Cannot read property 'getTargetNode' of undefined.
2. Warning: Failed context type: The context `popperManager` is marked as required in `Popper`, but its value is `undefined`.

**Comment by saurishkar** [comment]
@FezVrasta This is also reflecting when i am trying to use `<Popper>` component without the `<Target>` and `<Manager>` components.

**Comment by TheSharpieOne** [comment]
The examples were copied from master, but master is currently ahead of `react-popper@latest` on npm, which doesn't have the standalone feature.
We can either remove standalone (and standalone object) from the examples (for now) or set the version in the example to  `react-popper@latest`.

Note: The person who made the example in the link (forked the one from #85) should be able to save any changes without changing the URL which is in the repo description

**Comment by FezVrasta** [comment]
Fixed
