### ISSUE TITLE
Webpack warnings when using react-popper

### ISSUE THREAD

**Issue by PurpleGranite** [souporserious/react-popper#111]
### Issue description
react-popper is a dependency of reactstrap, which I am attempting to use in s SharePoint Framework project.  SharePoint Framework (SPFx) uses webpack extensively, and react-popper is causing webpack warnings which in turn lead to component load failures because react-popper has not been properly included in the output.

Discussion of this issue is linked to an open issue in the SharePoint Dev Docs repository, and while the original issue was thought to be a fault in upgrading SPFx to use React 16, investigation has indicated an issue specifically with react-popper - see [sp-dev-docs issue 1315](https://github.com/SharePoint/sp-dev-docs/issues/1315).

### CodePen demo
This is a build issue specific to use of react-popper in conjunction with other frameworks and cannot be reproduced in CodePen alone.

### Steps to reproduce the problem
1.  Create a new SharePoint Framework solution as per the standard guidelines
    a. Install gulp and the yeoman generator for SPFx: `npm -g install yo gulp @microsoft/generator-sharepoint`
    b. Create a new SPFx Web Part:  `yo @microsoft/sharepoint`, accept all defaults
2.  Update the `package.json` file to use React 16 and `npm update`
3.  Add bootstrap, jquery, reactstrap:  `npm install --save jquery bootstrap reactstrap`
    a. Note that recently released reactstrap@5.0.0 uses react-popper@0.8.3
4. Add any reactstrap component to the SPFx solution
5. Build and deploy per standard processes
    a. `gulp bundle`
    b. `gulp package-solution`
    c. `gulp serve --nobrowser`
6. Deploy per standard SharePoint Processes
7. Attempt to load the Web Part in a SharePoint Modern Experience page.

### What is the expected behavior?
It is expected that no warnings will be issued by webpack, and that the component will load correctly.

### What went wrong?
Webpack issues the following warnings during the bundle phase:
~~~
Warning - [webpack] 'dist':
./node_modules/react-popper/lib/Popper.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:/PROJECTS/Info.Insch.SpfxSandbox/node_modules/source-map-loader/index.js!D:/PROJECTS/Info.Insch.SpfxSandbox/node_modules/react-popper/lib/Popper.js
    Used by 1 module(s), i. e.
    D:/PROJECTS/Info.Insch.SpfxSandbox/node_modules/source-map-loader/index.js!D:/PROJECTS/Info.Insch.SpfxSandbox/node_modules/react-popper/lib/react-popper.js
* D:/PROJECTS/Info.Insch.SpfxSandbox/node_modules/source-map-loader/index.js!D:/PROJECTS/Info.Insch.SpfxSandbox/node_modules/react-popper/lib/popper.js
    Used by 2 module(s), i. e.
    D:/PROJECTS/Info.Insch.SpfxSandbox/node_modules/source-map-loader/index.js!D:/PROJECTS/Info.Insch.SpfxSandbox/node_modules/react-popper/lib/Popper.js
~~~

When loading the Web Part, SharePoint Framework issues the following error:
~~~
[SPLoaderError.loadComponentError]:
***Failed to load component "2a846d5b-9989-45cc-b7b8-68d8d4e8c231" (HelloWorldWebPart).
Original error: ***Failed to load entry point from component "2a846d5b-9989-45cc-b7b8-68d8d4e8c231" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/2a846d5b-9989-45cc-b7b8-68d8d4e8c231_0.0.1
	Cannot read property 'placements' of undefined

***INNERERROR:
***Failed to load entry point from component "2a846d5b-9989-45cc-b7b8-68d8d4e8c231" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/2a846d5b-9989-45cc-b7b8-68d8d4e8c231_0.0.1
	Cannot read property 'placements' of undefined
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.021/sp-pages-assembly_en-us_47a9581226d2ec9141d478f7998f2e4c.js:301:15646)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.021/sp-pages-assembly_en-us_47a9581226d2ec9141d478f7998f2e4c.js:700:37346)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.021/sp-pages-assembly_en-us_47a9581226d2ec9141d478f7998f2e4c.js:700:43235)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.021/sp-pages-assembly_en-us_47a9581226d2ec9141d478f7998f2e4c.js:700:39678)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-03-09.021/sp-pages-assembly_en-us_47a9581226d2ec9141d478f7998f2e4c.js:700:11287
    at <anonymous>
~~~

### Any other comments?
While the error reported when SPFx attempts to load the Web Part appear initially to be an SPFx issue, investigation has identified that the `placements` property which is the root cause of the load failure is from react-popper, and is related to the webpack warnings issued when generating the full output for the web part.

As far as I can see, this is because webpack is assuming the reference in react-popper's `Popper.js` file loading the 'real' popper.js is in fact a reference to the same file.

Do you have any suggestions which will allow react-popper to be successfully consumed by webpack?

Note that I cannot change away from webpack as this is an integral component of the SharePoint Framework.

**Comment by TheSharpieOne** [comment]
Did you see #76? Per the webpack config specific to the project, it tells webpack to look in the local directory first before looking in node modules (even if `./` is not in the path.)
Can you verify your webpack config is not doing this amd/or post it here?

**Comment by PurpleGranite** [comment]
The webpack config is buried deep inside the SPFx build process and not something I have direct / easy access to ... Will feed this back into the SPFx issue and see what pops up from there.

**Comment by FezVrasta** [comment]
There's not much we can do in this case, we don't have any duplicated file with just case differences.

**Comment by PurpleGranite** [comment]
@FezVrasta having done a lot of experimentation, I strongly believe that this issue needs to be re-opened.

Ultimately, the combination of packages that I'm using (SharePoint Framework, React, React DOM, Reactstrap, FontAwesome and others), _require_ that the webpack resolver modules paths contains `'.'`, without this in the path for example it is absolutely impossible to include a FontAwesome icon in a Reactstrap button, because react throws errors that are not thrown otherwise.

The ultimate fix is to use another name for your `Popper.js` file so that conflicts aren't an issue - changing configurations when those configuration changes are breaking changes for many other packages and package combinations isn't appropriate.

**Comment by FezVrasta** [comment]
I find it so difficult to think that you are the only one having this problem honestly... If enough people report this we can think about a solution. Until then, I'm convinced the problem is on your side.

**Comment by PurpleGranite** [comment]
@FezVrasta If you looked at the linked issue over at the SharePoint Framework side in my original report, you would see that I'm not the only one with this problem; and that it's not unique to my combination of packages.  Sure, people might not be reporting it directly here, but that's because they're indirectly consuming your package via npm's version of dependency hell, not using it intentionally or knowingly!

**Comment by FezVrasta** [comment]
It's still a problem of the sharepoint configuration, I mean, I don't even know what it's it, but if it happens only with it there must be a reason I guess?

How do you expect me to change the name of a file used in the library just because your configuration is trying to import stuff from where it's not supposed to?

**Comment by PurpleGranite** [comment]
So, instead of carrying out a relatively straightforward fix on your side which not only would resolve this issue but also prevent the same issue with the hundreds / thousands of potential package and configuration combinations out there, stopping lots of other developers falling into the same trap - often (as in this case) completely outwith their control, you opt to disown the problem and put it upon every potential consumer of your package to solve instead?

I have no direct control over the SharePoint Framework configuration; I'm just a consumer of that set of packages.

I have no direct control over how Reactstrap works, I'm just consuming that package,

I have no direct control over FontAwesome, again, just a consumer here.

I have no direct control over React ... guess what?  Yup, a consumer!

I shouldn't even have to care about all of that; especially as I'm not directly consuming react-popper - it's buried deep in a set of dependencies I also have no control over.

Surely it's a more 'customer focused' approach to just resolve the problem with the name conflicts than it is to force a mere consumer of packages to play piggy-in-the-middle between multiple projects, all the while wasting time and making no progress on their own projects?  If I gave an answer such as yours in my day job I'd soon not have a day job - so why is it OK for you to do so just because this project is open source?!

**Comment by FezVrasta** [comment]
I know I may be a "weird" person to talk to, but my point is:

> Why do I have to apply a _workaround_ when SharePoint could apply a **proper fix**?

We may fix the problem with `react-popper` renaming that file, and everybody would be happy and would go to get drunk and sing in the streets, but tomorrow some other package will make the same _mistake_, and everybody will be sad again. Is this where we want to go?

About all the day job stuff etc, if you are willing to pay me my hourly rate I'll be happy to show you all my professionality 😉

**Comment by PurpleGranite** [comment]
How about we balance your hourly rate with the several hundred hours I've already expended on this problem at my hourly rate?!

Or, better yet, how about you spend the 45 seconds it would take you to fix the issue!
