### ISSUE TITLE
Allow override modifiers?

### ISSUE THREAD

**Issue by borm** [souporserious/react-popper#112]
https://github.com/souporserious/react-popper/blob/master/src/Popper.jsx#L114

```jsx
const modifiers = {
  ...this.props.modifiers,
  applyStyle: { enabled: false },
  updateState: this._updateStateModifier,
}
```

--->

```jsx
const modifiers = {
  applyStyle: { enabled: false },
  updateState: this._updateStateModifier,
  ...this.props.modifiers,
}
```

**Comment by FezVrasta** [comment]
Without these 2 modifiers the component is not gonna work, why do you want to override them?

**Comment by borm** [comment]
because i have used `reactstrap` and i want set max height for very long dropdown menu

**Comment by borm** [comment]
Why it`s not worked?

simple example
```jsx
applyStyle: {
  enabled: true,
    fn: (data, options) => {
    console.log(data, options);
    return data;
  },
},
```

you should set notify for users who want override this modifier, about they should set `return data`

**Comment by FezVrasta** [comment]
Why can't you just create a new modifier that does that?

**Comment by borm** [comment]
[Updated](https://github.com/souporserious/react-popper/issues/112#issuecomment-376597981)
Resolved for me

**Comment by FezVrasta** [comment]
That's not a solution. 

Just create a new modifier like this:


```
setMaxHeight: {
  enabled: true,
  fn: (data, options) => {
    data.styles.maxHeight = '300px';
    return data;
  },
},
```

**Comment by borm** [comment]
But i don't see any problem to allow override `applyStyle` modifier like this
```jsx
const modifiers = {
  applyStyle: { enabled: false },
  ...this.props.modifiers,
  updateState: this._updateStateModifier,
}
```

or override all with call callback of updateState modifier from props

**Comment by borm** [comment]
oh thank you, I did not know that you can pass custom modifiers,
I'm just getting to know popper

**Comment by borm** [comment]
@FezVrasta, last question, how i can set position always to bottom or top?

like this
![image](https://user-images.githubusercontent.com/4027842/37994582-ac089fb6-321a-11e8-84c2-c0e6043f1245.png)

![image](https://user-images.githubusercontent.com/4027842/37994619-c40e8aee-321a-11e8-9d40-df78d83e3ff4.png)

and set translateX to 0 when reference element is attached to the edge of viewport

https://codesandbox.io/s/1ok99zrpxj

**Comment by FezVrasta** [comment]
```
flip: {
   behavior: ['top', 'bottom', 'top']
}
```

Is probably what you are looking for.

**Comment by borm** [comment]
![image](https://user-images.githubusercontent.com/4027842/38020657-7e65618e-3283-11e8-9141-fb403cafab71.png)
No, I want to see a dropdown always under or over of reference

**Comment by FezVrasta** [comment]
I don't think I get what you are looking for

**Comment by borm** [comment]
the problem is that dropdown overlaps the button.
dropdown should always be placed BELOW or ABOVE the button itself

**Comment by FezVrasta** [comment]
I think you want to disable the `preventOverflow` modifier then

**Comment by borm** [comment]
i think yes, but when i have disabled it, the dropdown in top button don't visible
