### ISSUE TITLE
Wrong poper position on first click

### ISSUE THREAD

**Issue by borm** [souporserious/react-popper#113]
### CodePen demo
https://react-popper-example-fies9l.stackblitz.io/

### Steps to reproduce the problem

1.  Scroll to **Toggleable Popper Example** or **Standalone Popper Example**
2.  Make sure what element have position to bottom of viewport, in my case 73px
3.  Click to reference
![image](https://user-images.githubusercontent.com/4027842/37996755-658bb2a6-3221-11e8-998e-053fa7918c8a.png)

### What is the expected behavior?
The poper should be displayed on top of reference

### What went wrong?
The poper displayed on first time on bottom, then change position to top of reference
![ezgif-5-9b3c4143e4](https://user-images.githubusercontent.com/4027842/37996860-d265a814-3221-11e8-9bd6-e50e10c4ee81.gif)

### Suggestion
set `visibility: hidden;` for poper initialize

**Comment by FezVrasta** [comment]
Oh... that's quite an edge case. Anyway I think the problem relies on Popper.js itself, may you open the issue in its repo? Thanks for the report.

**Comment by partyelite** [comment]
@borm  Did you solve this problem? Could you plz give an example how to solve it with setting visibility to hidden for poper initialize?

**Comment by borm** [comment]
nope

**Comment by drewlustro** [comment]
@borm the worst 👎
