### ISSUE TITLE
Can't access Popper.js placement values

### ISSUE THREAD

**Issue by privard** [souporserious/react-popper#114]
There is currently no way of retrieve the Popper.js placements values. IMO, either react-popper should export these values from Popper.js so clients can import them, or move Popper.js to peer-dependencies, so that clients can import their own PopperJS object and refer to it.

Thoughts?

**Comment by FezVrasta** [comment]
How would Popper.js as peerDependency help?

**Comment by TheSharpieOne** [comment]
If no other version of Popper.js is installed, npm will put the one for this package at the root of node_modules. It technically can be included without explicitly installing it at that point (but that seems fragile).
If the developer wanted to install Popper.js, they would need to ensure it is the same version that this package includes or there can be a chance of duplication if the versions are not the same (not a big deal but both version would be bundled in the end project and if the placements changed (unlikely, would probably be a major version bump) they could be different between the two versions. react-popper doesn't specify an exact version, so it's pretty broad. npm should be able to make sure the project's dep version and the project's dep's dep version are the same given they are within the same allowed range.
peerDependency would add an extra step and may not really solve the issue (especially is other packages also depend in it via regular dependencies).
I like the idea of react-popper just exposing the placements. It isn't much work or additional code for this project and ensures the placements exposed are valid placements for the underlying version of Popper.js.

**Comment by privard** [comment]
I agree that the peerDependency solution is probably not the best solution, because of version compatibility issues that might arise as a side-effect of the client installing the library. 

If we can expose react-popper's underlying instance, that would probably be best. Thanks for the prompt replies!

**Comment by DrDyne** [comment]
If the `PopperJS.placements` that is used [here](https://github.com/souporserious/react-popper/blob/master/src/Popper.jsx#L17) was exported, it would be easily accessible from outside as `import Popper, { placements } from 'react-popper'`.

**Comment by privard** [comment]
Wow, thanks @DrDyne!

**Comment by FezVrasta** [comment]
Implemented in 0.9.1
