### ISSUE TITLE
server side issue

### ISSUE THREAD

**Issue by oliviertassinari** [souporserious/react-popper#118]
I have noticed the following regression upgrading from 0.8.3 to 0.9.1. We can no longer render the component on the server.

![capture d ecran 2018-04-01 a 12 36 49](https://user-images.githubusercontent.com/3165635/38172268-685b808e-35a9-11e8-85f5-17be4f726ed8.png)

The error comes from this line. As you can imagine, `Element` isn't defined on Node.js.

https://github.com/souporserious/react-popper/blob/79544d780e33e1e49b9c15d0fa2bf1148641703c/src/Popper.js#L24

**Comment by FezVrasta** [comment]
Umh that type has not been changed in a while AFAIK... Anyway, are you running the code with the `NODE_ENV` variable set to `production`? The types should be stripped in that case.

**Comment by oliviertassinari** [comment]
> Umh that type has not been changed in a while AFAIK...

@FezVrasta It was introduced 10 days ago: #92. 

> Anyway, are you running the code with the NODE_ENV variable set to production?
The types should be stripped in that case. 

I'm happy to see the project is using my plugin :). But, I'm not running in production. I'm in dev mode.
https://github.com/souporserious/react-popper/blob/79544d780e33e1e49b9c15d0fa2bf1148641703c/package.json#L65

> But I don't know what's the best way to solve it.

Me neither. Maybe we can soften the type checking and compare the target with an object. It's what [we do on Material-UI side](https://github.com/mui-org/material-ui/blob/d2f1bda01645716d2f0452dda383ce52f46f8d9c/src/Portal/Portal.js#L68).

**Comment by FezVrasta** [comment]
Oh I did miss that change, sorry.

Well if we use `Object` as type I feel like we are just making the type check completely useless honestly 😓 May something like this work? (can you try on your project?)

```
PropTypes.instanceOf(typeof Element === 'function' ? Element : Object),
```

**Comment by oliviertassinari** [comment]
@FezVrasta It's working great on my project 👍

**Comment by FezVrasta** [comment]
Cool! Would you mind sending a PR with the fix?
