### ISSUE TITLE
null is not an object (reference.jquery)

### ISSUE THREAD

**Issue by chrisdrackett** [souporserious/react-popper#12]
I'm getting the following after updating to `0.5.0`:

`TypeError: null is not an object (evaluating 'reference.jquery')`

seems to be coming from here, unless something else is going on: https://github.com/FezVrasta/popper.js/blob/master/src/popper/index.js#L120

**Comment by chrisdrackett** [comment]
looks like this might be an issue on my end, I was using the following code:

```js
          <Target>
            {({ targetRef }) => (
              <Button
                label="button"
                ref={targetRef}
                onClick={this.togglePopover}
              />
            )}
          </Target>
```

but `Button` is a functional component, so won't work with refs

**Comment by souporserious** [comment]
Your code should work fine. I probably need to do some checks on my side in case the ref returns null like when the component unmounts. I'll look into it.

**Comment by chrisdrackett** [comment]
its ok, happy to help out :)

**Comment by souporserious** [comment]
Realized this probably a good error to have. Tried adding a warning, but since React will return null when the component is unmounted it didn't make sense and would show randomly.
