### ISSUE TITLE
Possible doc addition: sample usage with React portal functionality

### ISSUE THREAD

**Issue by unframework** [souporserious/react-popper#120]
There is a really helpful example in [this issue comment](https://github.com/souporserious/react-popper/issues/58#issuecomment-334120299) about how to use this library with the React portal feature to avoid `overflow: hidden` issues. Could be nice to add a version of that in the main readme so that it is obvious to folks that it is a use case that easily works out of the box. More of a newcomer intro/marketing suggestion, I guess?

And of course thanks for the library, it is much appreciated!

**Comment by FezVrasta** [comment]
We are working on a new API and documentation for the 1.x release, I'll make sure to add this example to it.

**Comment by unframework** [comment]
Thanks for the prompt response! Let me know if it's easy for me to just open a PR or if there is a specific doc style guide/etc. Cheers!

**Comment by FezVrasta** [comment]
No there's not any specific doc style guide, it's just that this API is going to be deprecated anytime soon and I don't think it's worth to spend more time on it.

**Comment by FezVrasta** [comment]
I just released the first beta of v1.x, the API should be stable now, please go ahead.

**Comment by FezVrasta** [comment]
added
