### ISSUE TITLE
Does not work with v1.14.2 of Popper.js

### ISSUE THREAD

**Issue by Maistho** [souporserious/react-popper#122]
### CodePen demo

I could for some reason not get it to show the error in the codepen when I tried earlier. Not sure exactly why.

But you can see the error here: https://reactstrap-error-tooltip.firebaseapp.com/

And the git repo is here: https://github.com/Maistho/reactstrap-tooltip-error

(I don't have the time right now, but I will try to create a new example that works in the codepen and without reactstrap tomorrow)

### Steps to reproduce the problem

1. Create a new app with create-react-app
2. add bootstrap and reactstrap
3. Add a tooltip
4. Tooltip does not appear in correct position

### What is the expected behavior?

Tooltip should appear in correct position

### What went wrong?
Seems like Popper.js changes the DOM after react-popper has written styles, and by doing that it overwrites the styles (but doesn't add them after)

### Any other comments?

See this issue for more information: https://github.com/reactstrap/reactstrap/issues/938

And it's definitely related to this piece of code: https://github.com/FezVrasta/popper.js/commit/7bfdedff75d694caef7ce30e3ab8c89df1b7f0bb

**Comment by ericgio** [comment]
I'm seeing the same issue. All the correct styles are being passed down to my popper component and I can see a flicker where it's correctly positioned for a split second, but then Popper.js seems to overwrite the values.

**Comment by TheSharpieOne** [comment]
I wonder if react-popper should clone the styles when the data is passed to it's modifier since Popper.js seems to mutate the values of the styles. That way it has its own copy of the most recent styles. Or is it too late by the time the modifiers run?

**Comment by Maistho** [comment]
@TheSharpieOne I don't think that would work since Popper.js modifies the DOM directly.

**Comment by FezVrasta** [comment]
I don't think there's anything that react-popper can do

**Comment by Maistho** [comment]
@FezVrasta I think that as long as react-popper can re-apply the styles after the DOM styles has been removed by Popper.js it should be fine. Could Popper.js perhaps add a hook that is run whenever the styles would be applied regularily?

**Comment by TheSharpieOne** [comment]
Oh, I see, react-popper is applying the styles correctly, but after the render Popper.js does its modification directly to the DOM. Wouldn't that affect more than react-popper's usage, or is it because react-popper has applyStyles set to false?

**Comment by FezVrasta** [comment]
May you guys test this version and tell me if it fixes your problem?

https://github.com/FezVrasta/popper.js/pull/599

**Comment by TLadd** [comment]
Pulled and linked the popper.js branch down and it does fix the problem I was seeing.

**Comment by FezVrasta** [comment]
Great! Going to release it soon

**Comment by grumd** [comment]
@FezVrasta by soon do you mean today? :)

**Comment by atomiks** [comment]
Sorry for the fix breaking everyone's projects 😞, at least now we've fixed the long-standing issue and thankfully react-popper could also be fixed.

**Comment by grumd** [comment]
@atomiks I'm out of the loop here, can you please point me to the issue you fixed in 1.14.2? Just curious

**Comment by atomiks** [comment]
@grumd see https://github.com/FezVrasta/popper.js/issues/251

Basically the popper would overflow the document boundaries on resize and more critically on update if the reference was close to the edge, causing it to not show fully.
