### ISSUE TITLE
Lock dependencies  "popper.js": "^1.14.1" - we experienced issues with popper.js 1.14.2

### ISSUE THREAD

**Issue by TheFullResolution** [souporserious/react-popper#123]
### CodePen demo

It is not easy to reproduce, but if you need this, I can work on it. 

### Steps to reproduce the problem

We are using Popper with react-portal if popper.js 1.14.2 is installed as a dependency (I can check it in yarn.lock) popper doesn't render next to the target but under a page, like a normal block.

### What went wrong?

When doing fresh yarn install (no yarn lock), 1.14.2 gets installed and seems to break how popper is rendered.

### Any other comments?

It is just a suggestion, but it would improve predictability of the package if dependency will be locked (remove the ^). If popper.js introduces breaking changes in the future whole react-popper could become unusable without manually editing yarn.lock or package.lock

**Comment by FezVrasta** [comment]
Please update to 1.14.3

I do my best to follow semver but the world is not bug-free 😔

If you want to have this kind of confidence you should lock the dependencies in your project using `yarn.lock` or the `npm-shrinkwrap.json` features of your package manager.

**Comment by TheFullResolution** [comment]
@FezVrasta I didn't realize that you are also a maintainer of popper.js. In this case, indeed locking it is not needed. Sorry for the unnecessary issue 😅
