### ISSUE TITLE
Safari popover jolt

### ISSUE THREAD

**Issue by willyyang** [souporserious/react-popper#126]
First off, thanks for making this package and I'm looking forward to seeing what the new updates have in store.

It seems like there's an initial jolt in the positioning of the arrow when I'm testing the popper on the latest Safari, any clue as to what could be wrong / what I should check to fix this? 

![screen shot 2018-04-04 at 6 49 31 pm](https://user-images.githubusercontent.com/6396257/38338814-33867dcc-3839-11e8-9e8c-7cb967fcd089.png)
![screen shot 2018-04-04 at 6 49 40 pm](https://user-images.githubusercontent.com/6396257/38338817-34fbcb30-3839-11e8-9b71-5113242ce9a1.png)
![screen shot 2018-04-04 at 6 51 52 pm](https://user-images.githubusercontent.com/6396257/38338832-40742f3e-3839-11e8-8d06-1c6d4e07930a.png)

Everything works great on the latest Chrome and FF

Cheers

**Comment by willyyang** [comment]
0.x

**Comment by FezVrasta** [comment]
Please open a new issue filling the issue template as asked. Thank you.
