### ISSUE TITLE
recalculate size of `Popper` when its contents change?

### ISSUE THREAD

**Issue by chrisdrackett** [souporserious/react-popper#15]
I just noticed that if I use the following code:

```js
  <Popper placement="top">
     {this.state.isOpen &&
        <div>test</div>
     }
  </Popper>
```

There are issues with the placement of the popper content. I'm guessing this is because the popper is being measured when it has no contents. In the simple case this is easy to fix by moving the conditional outside of the popper.

That being said, I did some more digging and found that if the contents of the `Popper` component change its size/position are not currently recalculated. It would be nice if the `Popper` component would handle updates to its contents.

**Comment by souporserious** [comment]
Just noticed that as well! Beat me to it before I could fix it 😆  working on fixing this for the next release.

**Comment by souporserious** [comment]
Fixed https://github.com/souporserious/react-popper/commit/2109ac0aa4210eafc668b3abe8d6e7a9ac2b2ada 🎉
