### ISSUE TITLE
Allow to pass as Target an object.

### ISSUE THREAD

**Issue by FezVrasta** [souporserious/react-popper#17]
This would rely on:
https://popper.js.org/popper-documentation.html#referenceObject

**Comment by souporserious** [comment]
What would this look like? `<Target reference={{...}}/>`?

**Comment by FezVrasta** [comment]
Up to you, I have no idea 😝

**Comment by souporserious** [comment]
I guess I'm not sure how it would work? Like what would a use case be for this? Maybe the child function gives you `clientWidth` and `clientHeight`, etc.

**Comment by FezVrasta** [comment]
Possible use cases are:
- pop a popper on the mouse position
- pop a popper relative to a custom area (for instance, some guys used this to make a tooltip appear near a text selection)

**Comment by souporserious** [comment]
Interesting.. so what parts need to care about this? Is this something both Target and Popper would use? Or just Popper? Trying to figure out where this fits best.

**Comment by FezVrasta** [comment]
The idea is to not have a target dom node at all, the popper will be the only dom node

**Comment by FezVrasta** [comment]
Maybe:

```
<Manager targetObject={{ bla }}>
  <Popper />
</Manager>
```

**Comment by kumarharsh** [comment]
Another use-case which I felt a need for is:

Say, you have a filter which opens a dropdown which would be the width of the app-container, and bounded by the app-container. In this case, I'll have to find the app-container's reference and pass **that** as the target, instead of an element I need to render...

**Comment by TheSharpieOne** [comment]
> Maybe:
> 
> ```
> <Manager targetObject={{ bla }}>
>   <Popper />
> </Manager>
> ```

Do you even need the manager? Couldn't you just pass it to `Popper`? Manager is really only connecting the `Popper` and `Target` so it doesn't make much sense without a DOM target rendered by `Target`. You would have to make the `popperManager` context not required and you could do something like:

```jsx
<Popper target={{ bla }}/>
```

Also, this would work great if the target could be a DOM node or something else, allowing users to attach a popper to existing elements anywhere on the page. You could even add a [helper](https://github.com/reactstrap/reactstrap/blob/681738c0182424d546d3b86ba15ce1f21e3b02a7/src/utils.js#L113-L127) to allow the target to be a string or something to select the target; if you wanted or leave that in user-land.

**Comment by ariroseonline** [comment]
@souporserious I'm looking into using react-popper, but the lack of followCursor makes it difficult to justify. Looks like there was a fork https://github.com/Gudahtt/react-popper/commit/9637b4d2611f0aae0989ba8bc3f1483fa73de122 which added support.

Is this safe to merge into master?

**Comment by Gudahtt** [comment]
Ah darn, I had meant to submit that as a PR but it slipped my mind. I'll review that tonight.

**Comment by ariroseonline** [comment]
@Gudahtt Thanks for helping out. I tried implementing your fork but ran into some problems in how to do it. E.g. Do you use a Manager? Does it it matter if you do or don't? What do you pass as the target prop in the case of trying to send the mouse position? 

Might be help to submit with a bit of documentation :)

**Comment by Gudahtt** [comment]
@ariroseonline Absolutely. The lack of documentation updates is why I didn't submit it as a PR yet. I'm working on that now.

**Comment by kumarharsh** [comment]
@FezVrasta AWESOME!!!
