### ISSUE TITLE
Alternative way to handle stateless components ref

### ISSUE THREAD

**Issue by FezVrasta** [souporserious/react-popper#18]
So, I recently updated one of my React utilities and I ended up needing to support the same case you struggled on.

The solution I reached is to ask for the custom component assigned to the `component` property to have a `getRef` property. It works very well and doesn't require `findDOMNode`.

https://github.com/FezVrasta/react-resize-aware/tree/master#self-containing

You may use a method like this instead of the current child function to make the API cleaner.

nb: In my case I also needed the custom component to have `children` defined, but for `react-popper` this isn't needed.

**Comment by souporserious** [comment]
I'd like to keep it the way it is since it is more clear the path you need to take. Trying to keep the API as simple as I can. By letting you access things in the child function you could essentially build your own wrapper if this is a necessity (not tested):

```js
function MyPopper({ children, ...props }) {
  return (
    <Popper {...props}>
      {(popperProps, restProps) => (
        React.cloneElement(React.Children.only(children), {...popperProps, ...restProps})
      )}
    </Popper>
  )
}
```
