### ISSUE TITLE
z-index?

### ISSUE THREAD

**Issue by chrisdrackett** [souporserious/react-popper#19]
My poppers are often showing up under other elements on the page. I'm trying to figure out a way to add a z-index to the popper, but figured it was worth asking here in case others have already solved this issue

**Comment by FezVrasta** [comment]
`z-index` is a sensitive problem and must be handled properly case by case.

That's why Popper.js doesn't set any `z-index` by default.

You should really end up with the best solution for you and manually set them I think.

**Comment by souporserious** [comment]
@chrisdrackett this was the exact reason for making everything compose-able :) you can add an inline style, classname or whatever you want.

I take an approach like this for any personal settings I want for components:
```js
const MyPopper = ({ style, ...props }) => <Popper style={{ zIndex: 100, ...style }} {...props}/>
```

**Comment by FO-Usain** [comment]
I have the same issue, but my Popover is the menu-list of mui-tel-input and I don't have access to the component in order for me to style it manually
