### ISSUE TITLE
modifier.function is deprecated, use modifier.fn

### ISSUE THREAD

**Issue by davekiss** [souporserious/react-popper#20]
I kept receiving this error in my console, I think it's due to this line:

https://github.com/souporserious/react-popper/blob/2109ac0aa4210eafc668b3abe8d6e7a9ac2b2ada/src/Popper.jsx#L76

Simply changed that to fn and error went away. Can you reproduce?

**Comment by holman** [comment]
Yeah, I'm getting it too; it's because of FezVrasta/popper.js#225.

**Comment by FezVrasta** [comment]
Actually it's a warning, not an error 🤓

By the way, yes, that's it. One of you could send a PR to update it.

**Comment by davekiss** [comment]
Sassy. I like it. PR submitted

**Comment by FezVrasta** [comment]
This should be closed since #22 has been merged

**Comment by souporserious** [comment]
Was going to wait until I released it on NPM :)

**Comment by nicmyers** [comment]
@souporserious Was there a plan to push out a new release to NPM?

**Comment by souporserious** [comment]
Sorry, pushed https://github.com/souporserious/react-popper/commit/0115651a04b27dcb80a7398f4e75f13f5a2eaf59
