### ISSUE TITLE
jquery null ref

### ISSUE THREAD

**Issue by SpencerCDixon** [souporserious/react-popper#25]
I'm probably missing something fairly obvious here... but I'm trying to make a tooltip style popper and I keep getting some jquery error:
![screen shot 2017-06-13 at 10 57 20 am](https://user-images.githubusercontent.com/7471018/27088967-1ca2d0e2-5027-11e7-996c-b430d195a617.png)

Component code:

```js
class InfoTip extends Component {
  state = {
    visible: false,
  }

  onMouseOver = () => {
    this.setState({visible: true});
  }

  onMouseOut = () => {
    this.setState({visible: false});
  }

  render() {
    return (
      <Manager>
        <Target>
          {({targetProps}) => {
            return (
              <InfoIcon
                dark
                style={{cursor: 'help'}}
                onMouseEnter={this.onMouseOver}
                onMouseLeave={this.onMouseOut}
                {...targetProps}
              />
            );
          }}
        </Target>

        {this.state.visible && (
          <Popper placement="right" className="popper">
            {this.props.children}
            <Arrow className="popper__arrow"/>
          </Popper>
        )}
      </Manager>
    );
  }
}
```

Any thoughts?

**Comment by FezVrasta** [comment]
Seems like react-popper can't get your target element, I think you should assign `targetProps.ref` to a property of your InfoIcon component that proxies the `ref` of its internal element.

**Comment by SpencerCDixon** [comment]
ahhh yes, so it looks like because InfoIcon was a functional stateless comp it wasn't working.  I added a span around it and tied the targetProps to that and it seems to work now, thanks for the direction!

**Comment by programstinator** [comment]
Hi there, I'm having a similar issue when using react-travel to render the Popper outside my component. To be clear, the code works in the browser I only get the errors when running Jest snapshot tests. 
This is what the error looks like: 
![image](https://user-images.githubusercontent.com/2131998/29820778-e509d7d0-8cc5-11e7-9abd-ff0d824e7182.png)
My code looks like this:
`<Manager className='ifl-component ifl-dropdown'>
      <Target>
        <DropdownInput
          name={name}
          storeName={storeName}
          className={className}
          refCallbackFocusElement={localState.refCallbackFocusElement}/>
        {localState.isClearable && <DropdownClearButton name={name} storeName={storeName}/>}
        <DropdownArrowButton name={name} storeName={storeName}/>
      </Target>
      <Portal>
        <Popper placement={'bottom-start'} className='ifl-dropdown-options' modifiers={popperModifiers}>
          <DropdownOptions name={name} storeName={storeName}/>
        </Popper>
      </Portal>
    </Manager>`

**Comment by programstinator** [comment]
Neverming, I figured it out. React-travel has a prop called 'useArray' which, when absent, causes the Protal to render as 'null' which caused the jQuery error from above.
