### ISSUE TITLE
bump to version 1.10.2

### ISSUE THREAD

**Issue by mikkelwf** [souporserious/react-popper#27]
Hey..

Can you update to version 1.10.2.
It solves an issue i reported, so an update is much appreciated... :)

**Comment by FezVrasta** [comment]
The package doesn't lock to a specific version of Popper.js, you can upgrade the dependencies and get the latest.

https://github.com/souporserious/react-popper/blob/master/package.json#L43

**Comment by mikkelwf** [comment]
thanks.. i'll give it a try..
