### ISSUE TITLE
Add helpful warnings

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-popper#28]
Better dev experiences help when coding. I love what React Router does [here](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L64-L77). Let's copy that :)

**Comment by FezVrasta** [comment]
Added, the only place where it made sense to me was in the `Reference` component, that now will warn if it's being used outside of `Manager`.

`Popper` can work alone, and `Manager` doesn't have any specific requirement.
