### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-popper#29]
I'd like to use Jest. Don't have time right now to set this help. Any help setting this up is greatly appreciated :)

**Comment by jdalino** [comment]
Hi @souporserious i'd like to help out in setting this up

**Comment by souporserious** [comment]
That would be amazing! Please let me know anything you need. Feel free to start a PR and we can work through it together if you would like.

**Comment by miketmoore** [comment]
@jdalinoboom @souporserious let me know if I can help!

**Comment by souporserious** [comment]
I definitely will! Going to work on rewrite to fix some outstanding issues then I'll probably need help writing tests 😇
