### ISSUE TITLE
Popper component not positioned to target component correctly (in multiple manager instances)

### ISSUE THREAD

**Issue by tohjustin** [souporserious/react-popper#30]
**Steps to reproduce:** 
1. Modify the `<App />` component in [/example/index.jsx](https://github.com/souporserious/react-popper/blob/master/example/index.jsx)
```JavaScript
const App = () =>
  <div
    style={{
      padding: 200,
    }}
  >
    <div style={{ marginBottom: 200 }}>
      <MultipleExample />
    </div>
    <div style={{ marginBottom: 200 }}>
      <AnimatedExample />
      <AnimatedExample /> // popper rendered in incorrect position
      <AnimatedExample /> // popper rendered in incorrect position
    </div>
  </div>
ReactDOM.render(<App />, document.getElementById('app'))
```
2. Popper rendered in incorrect position, not directly above the <Target /> component (purple box)
<img width="317" alt="screenshot" src="https://user-images.githubusercontent.com/8844886/27551511-901a3f02-5a58-11e7-91ee-1ec9e52b6e62.png">

**Comment by FezVrasta** [comment]
Are you able to reproduce the problem with just Popper.js? I don't think this problem is directly related to `react-popper`.

**Comment by tohjustin** [comment]
@FezVrasta Thanks for the quick follow up! Will try to reproduce it w/ Popper.js & post a jsFiddle example when I get back home tonight...

**Comment by souporserious** [comment]
Following this. Please let me know anything you need on my end. Unfortunately busy right now, but I'll help push anything through where I can.

**Comment by tohjustin** [comment]
@souporserious Thanks for responding! Haven't got the chance to confirm the cause of this behavior, will keep you guys updated =)

**Comment by tohjustin** [comment]
@souporserious @FezVrasta Here's an attempt to reproduce the same thing in vanilla javascript... https://jsfiddle.net/tohjustin/fqjbsu5L/

**Comment by FezVrasta** [comment]
Am I missing something or is it working?

**Comment by tohjustin** [comment]
It looks okay when you zoom out:
<img width="1279" alt="works if you zoom out" src="https://user-images.githubusercontent.com/8844886/27599886-02b668c6-5b1f-11e7-8bf6-90a9dd7b6e19.png">

But when you start zooming in, it gets some weird non-deterministic behavior:
<img width="1279" alt="gets a bit wierd when you zoom in" src="https://user-images.githubusercontent.com/8844886/27599887-02b80b04-5b1f-11e7-97bf-9335683d7e56.png">

@FezVrasta Not sure where to start looking at, cause it feels more like the `react-popper` referencing the incorrect targets when I try to use it over here: 
- https://github.com/tohjustin/react-datepicker/tree/issue-905
    - If you have a minute or two, you can try cloning the branch, `yarn run start` & see the same "bug" in `localhost:8080`
    - The page in `localhost:8080` uses a lot of poppers, & all the poppers (starting from the 3rd one) seems to be anchoring to the same wierd position...

<img width="866" alt="weird anchoring" src="https://user-images.githubusercontent.com/8844886/27600964-762e6fbc-5b22-11e7-95fe-03bb722914dc.png">

**Comment by FezVrasta** [comment]
So does it happen only when you use the zoom?

**Comment by tohjustin** [comment]
The bug was visible in the default (100%) zoom level, so I tried playing with other zoom levels but it was still there. 

The jsFiddle example @ https://jsfiddle.net/tohjustin/fqjbsu5L/ seems to work in **50% zoom** & below, but the calendar example above doesn't work at any zoom levels

**Comment by FezVrasta** [comment]
I see this on 100% zoom

![image](https://user-images.githubusercontent.com/5382443/27601976-7a9f3c8a-5b71-11e7-8c68-ae36aaa1f03f.png)

**Comment by tohjustin** [comment]
@FezVrasta Just found out that the weird stuff I'm getting in my jsFiddle example (on my side) was b/c the popper was flushed to a badly styled body element (I think you should be able to get something similar if you resize your window but keep the zoom @ 100%)

![flushing to body element](https://user-images.githubusercontent.com/8844886/27602662-690a648e-5b28-11e7-8012-586fbea6e354.png)

**Comment by tohjustin** [comment]
Just confirmed that the problem was due to the following style:
```css
body {
    height: 100%;
}
```

The popper ended up in a weird position b/c it was flushed to the boundary of the `body` element (for the jsFiddle, react-popper example & calendar example)

I guess `react-popper` & `popper.js` were working as intended (will double check on this tonight).

@FezVrasta So sorry for the false alarm =( Really appreciate the time you've spent following up on this!

**Comment by FezVrasta** [comment]
Cool, actually Popper should use the viewport as constraint (or the document...?).

It seems related to somehow
https://github.com/FezVrasta/popper.js/issues/302
