### ISSUE TITLE
react-popper and react 15.6.1 and react-dom 15.6.1

### ISSUE THREAD

**Issue by hannehofmann** [souporserious/react-popper#31]
warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: boolean.

react-dom.min.js:15 Uncaught Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=boolean&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (react-dom.min.js:15)
    at p.i [as _instantiateReactComponent] (react-dom.min.js:15)
    at performInitialMount (react-dom.min.js:13)
    at p.mountComponent (react-dom.min.js:13)
    at Object.mountComponent (react-dom.min.js:14)
    at mountChildren (react-dom.min.js:14)
    at m._createInitialChildren (react-dom.min.js:13)
    at mountComponent (react-dom.min.js:13)
    at Object.mountComponent (react-dom.min.js:14)
    at performInitialMount (react-dom.min.js:13)

**Comment by FezVrasta** [comment]
without a reproducible example I hardly believe we'll be able to find your problem

**Comment by hannehofmann** [comment]
Hey FezVrasta,

I have updated react, react-dom and react-addons-test-utils from version 15.3.0 to 15.6.1. In course of that I have replaced the deprecated React.PropTypes with the explicit prop-types package. Afterward I've gotten this error. In Hope to fix it I've upgrade popper.js from 1.8.1 to 1.10.8 aner react-popper from 0.4.3 to 0.7.0.

resulting package.json:

{
  "repository": { ... },
  "keywords": [
    "gulp",
    "browserify",
    "sass",
    "javascript"
  ],
  "scripts": { ... },
  "engines": {
    "node": "~5.1.0"
  },
  "licence": "private",
  "dependencies": {
    "axios": "^0.15.3",
    "babel-polyfill": "^6.23.0",
    "classnames": "^2.2.5",
    "conduitjs": "^0.3.3",
    "cookies-js": "^1.2.3",
    "immutable": "^3.8.1",
    "jquery": "^1.12.2",
    "lodash": "^4.17.4",
    "lodash.noop": "^3.0.1",
    "lodash.throttle": "^4.1.1",
    "parser-front-matter": "^1.6.2",
    "parsley": "^0.1.0",
    "parsleyjs": "^2.6.2",
    "photoswipe": "^4.1.1",
    "popper.js": "^1.10.8",
    "postal": "^2.0.5",
    "postal.preserve": "^0.2.0",
    "react-click-outside": "^2.3.0",
    "react-google-maps": "^7.0.0",
    "react-input-range": "^0.9.1",
    "react-popper": "^0.7.0",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0",
    "selectric": "git+https://github.com/lcdsantos/jQuery-Selectric.git#1.10.1",
    "slick-browserify": "^1.5.9"
  },
  "devDependencies": {
    "ajv": "^4.11.3",
    "async": "^2.0.0-rc.3",
    "autoprefixer": "^6.3.6",
    "axios": "^0.15.3",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-jest": "^18.0.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-es2015-loose": "^8.0.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-1": "^6.16.0",
    "babel-register": "^6.18.0",
    "babelify": "^7.2.0",
    "backstopjs": "^2.6.6",
    "body-parser": "^1.16.0",
    "browser-sync": "^2.18.8",
    "browserify": "^14.1.0",
    "browserify-global-shim": "^1.0.3",
    "browserify-shim": "^3.8.12",
    "cors": "^2.8.1",
    "css-mqpacker": "^5.0.1",
    "deep-equal": "^1.0.1",
    "deep-extend": "^0.5.0",
    "del": "^2.2.0",
    "enzyme": "^2.9.1",
    "enzyme-to-json": "^1.5.1",
    "eslint": "^3.18.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-immutable": "^1.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsdoc": "^2.3.1",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.0.0",
    "express": "^4.14.0",
    "fs": "0.0.1-security",
    "fs-utils": "^0.7.0",
    "get-value": "^2.0.6",
    "git-guppy": "^2.0.0",
    "glob": "^7.0.3",
    "gulp": "^3.9.1",
    "gulp-changed": "^2.0.0",
    "gulp-chug": "^0.5.1",
    "gulp-data": "^1.2.1",
    "gulp-debug": "^3.1.0",
    "gulp-eslint": "^3.0.1",
    "gulp-extname": "^0.2.2",
    "gulp-favicons": "^2.2.7",
    "gulp-file": "^0.3.0",
    "gulp-front-matter": "^1.3.0",
    "gulp-hb": "^5.1.4",
    "gulp-htmlmin": "^3.0.0",
    "gulp-iconfont": "^8.0.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^3.1.1",
    "gulp-json-to-sass": "0.0.4",
    "gulp-layouts": "^0.1.0",
    "gulp-newer": "^1.3.0",
    "gulp-notify": "^3.0.0",
    "gulp-nunjucks-render": "https://github.com/carlosl/gulp-nunjucks-render#2.0.0",
    "gulp-plumber": "^1.1.0",
    "gulp-postcss": "^6.1.0",
    "gulp-real-favicon": "^0.2.2",
    "gulp-rename": "^1.2.2",
    "gulp-rev": "^7.0.0",
    "gulp-rev-napkin": "^0.1.0",
    "gulp-rev-replace": "^0.4.3",
    "gulp-sass": "^3.1.0",
    "gulp-sequence": "^0.4.5",
    "gulp-sizereport": "^1.1.3",
    "gulp-sourcemaps": "^2.4.1",
    "gulp-streamify": "^1.0.2",
    "gulp-uglify": "^2.0.1",
    "gulp-util": "^3.0.7",
    "gulp-watch": "^4.3.5",
    "guppy-pre-push": "^0.2.1",
    "handlebars": "4.0.6",
    "handlebars-helpers": "^0.8.0",
    "icu-loader": "^2.0.3",
    "imagemin-pngquant": "^5.0.0",
    "is-number": "^3.0.0",
    "jest": "^18.1.0",
    "layouts": "^0.13.2",
    "merge-stream": "^1.0.0",
    "normalize-path": "2.0.1",
    "object.entries": "^1.0.4",
    "open": "0.0.5",
    "postcss-pxtorem": "^4.0.0",
    "postcss-reporter": "^3.0.0",
    "postcss-scss": "^0.4.1",
    "pretty-hrtime": "^1.0.2",
    "prop-types": "^15.5.10",
    "qs": "^6.4.0",
    "react": "15.6.1",
    "react-addons-test-utils": "15.6.0",
    "react-dom": "15.6.1",
    "react-redux": "^5.0.2",
    "react-router": "^4.0.0",
    "react-test-renderer": "^15.6.1",
    "redux-responsive": "^4.1.1",
    "require-dir": "^0.3.0",
    "retire": "^1.2.12",
    "sass-mq": "^3.2.9",
    "streamify": "^0.2.5",
    "striptags": "^2.2.1",
    "stylelint": "^7.9.0",
    "swag": "^0.7.0",
    "through2": "^2.0.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.7.0"
  },
  "browserify-shim": {
    "jquery": "global:$"
  },
  "browserify-global-shim": {
    "immutable": "Immutable",
    "react": "React",
    "react-dom": "ReactDOM",
    "react-redux": "ReactRedux",
    "redux": "Redux",
    "axios": "axios",
    "postal": "postal",
    "parsleyjs": "Parsley",
    "prop-types": "PropTypes",
    "handlebars": "Handlebars"
  },
  "browserify": {
    "transform": [
      "browserify-shim",
      "browserify-global-shim"
    ]
  },
  "jest": {
    "setupFiles": [
      "./test/jest-setup.js"
    ],
    "collectCoverageFrom": [
      "src/components/**/*.{js,jsx}",
      "!**/node_modules/**",
      "!**/vendor/**",
      "!src/components/organisms/styleguide-nav/styleguide-nav.js",
      "!src/components/organisms/search/partials/action-types.js",
      "!src/components/organisms/basket/partials/action-types.js",
      "!src/components/**/styleguide.js",
      "./test/jest.js"
    ],
    "snapshotSerializers": [
      "<rootDir>/node_modules/enzyme-to-json/serializer"
    ]
  }
}

resulting issue:
<img width="859" alt="bildschirmfoto 2017-07-05 um 07 31 48" src="https://user-images.githubusercontent.com/5858048/27850317-1565382c-6154-11e7-974c-4b77ea0ffafb.png">


Hope you can help me to find the issue,

BR Hanne

**Comment by souporserious** [comment]
Unfortunately, there is not enough provided information to help diagnose the problem. Please feel free to reopen this issue if you can provide a Codepen example, or an isolated repo with a reproducible issue. Thank you.
