### ISSUE TITLE
Uncaught at dispatch TypeError: Cannot read property 'scheduleUpdate' of undefined

### ISSUE THREAD

**Issue by guillaumepotier** [souporserious/react-popper#32]
Hi,

I'm facing a console bug with Popper [at that line](https://github.com/souporserious/react-popper/blob/b3e0f32813dac0779f06d569ef456af29551add3/src/Popper.jsx#L57)

Dunno why, and things seems to work smoothly despite that error.

Should not we test `this._popper` before, like done above in the file?

**Comment by souporserious** [comment]
Should be fixed with https://github.com/souporserious/react-popper/pull/38 thank you 🙏
