### ISSUE TITLE
Popper is not offsetting for arrow size when Arrow is a react component

### ISSUE THREAD

**Issue by SpadarShut** [souporserious/react-popper#33]
So my code looks like this:
```
  render() {
    const { target, menu, config } = this.props;
    return (
      <Manager {...config.manager}>
        <Target {...config.target} >
          {target}
        </Target>
        <Popper {...config.popper}>
          {menu}
          <Arrow {...config.arrow} />
        </Popper>
      </Manager>
    );
  }
```

where 
```
config.arrow = {
    component: MenuArrow
}
```
The `MenuArrow` is rendering, but the popper position does not adjust for its size. If I set some widht and height directly on `Arrow`, then it works as expected.

**Comment by souporserious** [comment]
Is it possible you can create a Codepen or a repo with the issue isolated? @FezVrasta any idea what might be causing this?

**Comment by FezVrasta** [comment]
Maybe this?
https://github.com/FezVrasta/popper.js/issues/343

**Comment by SpadarShut** [comment]
Yes, looks like the same issue. But somehow, the Popper gets offset if I use <Arrow style={{height: 10}} />

**Comment by FezVrasta** [comment]
so weird, if you could be able to reproduce the problem with Popper.js without any React code it would help to understand why this happens.

**Comment by souporserious** [comment]
Is this related https://github.com/souporserious/react-popper/issues/54?

**Comment by souporserious** [comment]
Closing since this has been inactive, please feel free to reopen with a code example so we can diagnose the issue further if it is still present.
