### ISSUE TITLE
allow Arrow to offset both left and top

### ISSUE THREAD

**Issue by giladgray** [souporserious/react-popper#34]
seems somewhat unnecessary to only support left OR top offset for arrow, but not both: https://github.com/souporserious/react-popper/blob/master/src/Popper.jsx#L155-L159

I'm writing a modifier to dynamically offset the popper on the alternate axis and counter-offset the arrow on the same axis, instead of relying on CSS margins etc, but react-popper actively fights this.

Is it fair to just do the simple thing and simply apply `top` and `left` offsets at all times?

**Comment by souporserious** [comment]
Interesting 🤔 I haven't run into this yet. I'm open to adding it if it's needed for modifiers. @FezVrasta do you have an opinion on this?

**Comment by giladgray** [comment]
give me the 🍏 and i'll submit a PR 👍

**Comment by FezVrasta** [comment]
react-popper should simply apply any style defined in the styles objects of arrow and popper elements. So yes, I this it would make sense to allow the OP's modifier to work.

Also, please @giladgray, consider to release the modifier on npm, I think it may be useful for others.

If it's not much code we may directly integrate the changes in the existing arrow modifier.

**Comment by giladgray** [comment]
worth noting that popper.js itself does not make such a distinction: it'll apply any and all styles in `data.offsets.arrow`

https://github.com/FezVrasta/popper.js/blob/c56272aa65bd016bb9a9a2e28b8c63c5b01537fc/packages/popper/src/modifiers/applyStyle.js#L27-L29

**Comment by giladgray** [comment]
@FezVrasta it'll be a part of Blueprint's `Popover` rewrite and has some use-case-specific logic (we use SVG for the arrow and rotate it 45deg so there's some `sqrt(2)` math involved). hang on tight for that PR!

**Comment by giladgray** [comment]
> react-popper should simply apply any style defined in the styles objects of arrow and popper elements.

@FezVrasta there does not seem to be an arrow `styles` object from `computeStyle`... it just outputs one `data.styles` object for the popper itself 🤔

**Comment by souporserious** [comment]
@giladgray interested in your solution to position the arrow, do you have any sample code you can point to? I'd love to integrate that in my own stuff 😁
