### ISSUE TITLE
include typescript typings

### ISSUE THREAD

**Issue by giladgray** [souporserious/react-popper#35]
@souporserious would you be open to including a `.d.ts` file in the NPM package for typescript consumers? i've been writing it locally and would be happy to contribute. 

there'd be some additional maintenance cost to keep the definitions updated as the API evolves, but I'll be happy to help out if you mention me in the future!

**Comment by souporserious** [comment]
Yeah for sure :) I don't know much about typescript, but I'd be happy to accept a PR for it.

**Comment by giladgray** [comment]
cool i'll send it up once i'm happy with what i've got!

thanks for speedy replies 😃
