### ISSUE TITLE
Avoid wrapping div if single child is provided

### ISSUE THREAD

**Issue by FezVrasta** [souporserious/react-popper#42]
Take this case in consideration:

```
<Manager>
  <Something>
    <Target />
    <Popper />
  </Something>
</Manager>
```

this will generate the following markup:

```
<div>
  <div>
    <div />
    <div />
  </div>
</div>
```

In this case tho, we could avoid to generate the top wrapping `div`, because `Manager` is going to render a single child.

I think we could support this case.

**Comment by souporserious** [comment]
Would passing `<Manager tag={false}/>` work here? You can [read about it in the docs](https://github.com/souporserious/react-popper#tag-proptypesoneoftypeproptypesstring-proptypesbool).

**Comment by FezVrasta** [comment]
Oh yes exactly lol
