### ISSUE TITLE
Popper passes down unknown props to html tags.

### ISSUE THREAD

**Issue by Eldwick** [souporserious/react-popper#52]
`Popper` is currently passing down `restProps` (or all unused props of `Popper`) to it's direct child here: 
https://github.com/souporserious/react-popper/blob/master/src/Popper.jsx#L207

This causes the following warning if a user-defined `component` attribute is not passed down or an html tag is specified as the `component` prop:

```
Warning: Unknown prop 'closePortal' on <div> tag.
```

I suggest that `restProps` should only be passed down if the `component` is a user-defined react component not an html tag.

**Comment by souporserious** [comment]
I'm not sure I follow, do you have an example of what you are working with? I think you may be able to just not pass those props to the Popper component.

**Comment by TheSharpieOne** [comment]
@Eldwick have you tried not passing in props you don't want rendered? What react-popper does here is fairly standard. In fact, I would call it a bug if it didn't pass down the props. GIGO
