### ISSUE TITLE
arrowStyle props not being passed to Arrow component

### ISSUE THREAD

**Issue by darknoon** [souporserious/react-popper#54]
I'm trying to have an arrow next to a popover that moves with the popover. This seems to be supported in vanilla Popper.js, and the relevant code [seems to be present](https://github.com/souporserious/react-popper/blob/b3e0f32813dac0779f06d569ef456af29551add3/src/Arrow.jsx#L13) in `react-popper` to pass the style computed from Popper down into the `Arrow` component, however in my app, I see `style={}` on that component.

I used some logs and the debugger to try to narrow down the issue: I think Popper is mounting and implicitly `Arrow` needs to re-render to consider the new props passed in via style. However, it doesn't rerender:

```
15:57:51.482 Popper.js:112 getChildContext Popper {props: {…}, context: {…}, refs: {…}, updater: {…}, state: {…}, …}
15:57:51.498 Popper.js:96 _getArrowStyle Popper {props: {…}, context: {…}, refs: {…}, updater: {…}, state: {…}, …}
15:57:51.522 Popper.js:144 _updatePopper Popper {props: {…}, context: {…}, refs: {…}, updater: {…}, state: {…}, …}context: {popperManager: {…}}props: {placement: "right", children: {…}, component: "div", eventsEnabled: true, modifiers: {…}}refs: {}state: {data: {…}}updater: {isMounted: ƒ, enqueueCallback: ƒ, enqueueCallbackInternal: ƒ, enqueueForceUpdate: ƒ, enqueueReplaceState: ƒ, …}_arrowNode: div.settings_editor_arrow_getArrowStyle: ƒ ()_getPopperPlacement: ƒ ()_getPopperStyle: ƒ ()_getTargetNode: ƒ ()_node: div_popper: Popper {options: {…}, state: {…}, reference: div, scheduleUpdate: ƒ, update: ƒ, …}_reactInternalInstance: ReactCompositeComponentWrapper {_currentElement: {…}, _rootNodeID: 0, _compositeType: 0, _instance: Popper, _hostParent: ReactDOMComponent, …}_setArrowNode: ƒ (node)_updateStateModifier: {enabled: true, order: 900, fn: ƒ}isMounted: (...)replaceState: (...)__proto__: ReactComponent
15:57:51.524 Popper.js:153 creating popper
15:57:51.535 Popper.js:112 getChildContext Popper {props: {…}, context: {…}, refs: {…}, updater: {…}, state: {…}, …}
15:57:51.541 Popper.js:112 getChildContext Popper {props: {…}, context: {…}, refs: {…}, updater: {…}, state: {…}, …}
```

My best understanding of the issue is that React doesn't know that `componentDidMount()` implicitly means that `Arrow` must rerender, thus Arrow is stuck behind.

If I manually click on `MyArrowComponent` instance in the React devtools and type  `$r.forceUpdate()` I can get it to have the correct behavior.

**Comment by darknoon** [comment]
I was thinking as a possible solution I could have Arrow return a class that keeps state around, and register with the Popper to get updated when the style updates à la Redux `connect()` HOC.

**Comment by souporserious** [comment]
🤔 this is really weird. The `Arrow` component should be updating since it's a child of `Popper`, and when `Popper` gets new data it sets the new state and should cause a re-render. @FezVrasta is it possible we need to check for more than `data.offsets` changes in the `_updateStateModifier` function?

**Comment by darknoon** [comment]
@souporserious that wasn't the issue; you can have it always update and you will still observe this bug.  the Popper itself may update, but it wouldn't cause the Arrow element to get recreated because that's passed in. Maybe you require all children to be functions going up to the `<Popper>`? I didn't remember that being documented, though.

I should re-test to see if that case works, but it seems like a significant limitation / impedance mismatch with the rest of our team's React codebase.

**Comment by souporserious** [comment]
I just pushed a release with hopefully a better system of checking for changes. Can you please test to see if this might have fixed your issue? Also, any chance you have some example code that causes the issue so I can reproduce?

**Comment by darknoon** [comment]
@souporserious do you have a test case for Arrow I could start from? Wouldn't be that hard to make a specific test case but if you already have something close I could modify that. Specifically where an element is in a scroll that has a popper attached (hence arrow needing to update)

**Comment by souporserious** [comment]
I don't have anything right now, I will try and pull an example from the PopperJS repo so I can make sure it works properly.
