### ISSUE TITLE
Type definitions doesn't work with latest version of popper.js

### ISSUE THREAD

**Issue by sergeykaikin** [souporserious/react-popper#56]
"popper.js" type definitions have been updated recently and they are braking "react-popper"  type definitions. I am getting:

```
Namespace ''popper.js'' has no exported member 'Placement'.
Namespace ''popper.js'' has no exported member 'Modifiers'.
```

They have introduced braking changes in 1.11.1. Why don't you lock your "popper.js" to "1.11.0"?

**Comment by pmoleri** [comment]
This is addressed in PR #51 awaiting to be merged.

In the time being, you can work around it writing a module augmentation:
```typescript
declare module 'popper.js' {
    /* This augments the popper.js module, because in the installed version 
    Placement and Modifiers interfaces are exported under the default exported value,
    but react needs the declaration as it is defined here. */

    import PopperJS from "popper.js";

    export type Placement = PopperJS.Placement;
    export type Modifiers = PopperJS.Modifiers;
}
```
And save it to a file like: `popper-augmentation.d.ts` where your source files are.

Or locking to `popper.js@1.11.0` in your own `package.json` and reinstalling from scratch to make npm dedupe that dependency.

**Comment by souporserious** [comment]
I _think_ this is fixed in the latest release with this PR https://github.com/souporserious/react-popper/pull/51 please feel free to reopen this issue if not.

**Comment by pmoleri** [comment]
Thanks! Already tried it, seems to be working just fine.
