### ISSUE TITLE
Investigate new portals in React 16

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-popper#58]
It would be cool if we could make this really easy and have a prop that passes down the id of a container or something similar to render `<Popper/>` components into.

**Comment by FezVrasta** [comment]
I wouldn't add too much functionalities here honestly. I like specialized components

**Comment by fernandopasik** [comment]
Would it be possible to first update to react 16 before going into this?

**Comment by FezVrasta** [comment]
For React 16 I did prepare a small test PR while it was still in beta.

https://github.com/souporserious/react-popper/issues/58

**Comment by TheSharpieOne** [comment]
Just FYI, reactstrap uses react-popper and did something similar (wasn't that hard), though I wouldn't use the new portals exclusively or you will break backwards compatibility which is :cry:. Maybe another library/component which depends on react-popper can be created which just adds this feature (like react-popper-portal).
Anyways, came here searching for react 16 support. Can just a simple release be created adding peerDep which includes 16 (everything works great as is, just would like npm to stop complaining)?

**Comment by jamiewinder** [comment]
I'm already using `react-popper` with React 16's portals:

With a simple 'Portal' component:

```typescript
class Portal extends React.Component {
    render() {
        const { children, target = document.body } = this.props;
        return ReactDOM.createPortal(children, target);
    }
}
```
You can simply do:
```xml
<Manager tag={false}>
    <Target>
        <div>This target...</div>
    </Target>
    <Popper>
        <Portal>
            <div>... has this popper</div>
        </Portal>
    </Popper>
</Manager>
```

**Comment by souporserious** [comment]
After thinking about it, I agree it shouldn't go in here since it's so trivial and would break backwards compatibility 💩
