### ISSUE TITLE
Dynamic content size

### ISSUE THREAD

**Issue by jamiewinder** [souporserious/react-popper#60]
If I have some popper content that can change size (which could possibly result in the 'correct' position of the popper changing), what is the best way to handle this in this library? I assume the correct way in plain Popper.js is to call `scheduleUpdate` on the Popper instance, but I don't think I have access to that with react-popper?

**Comment by FezVrasta** [comment]
You should have access to the `scheduleUpdate` method already.

You can then combine react-popper with react-resize-aware:

```jsx
<Popper>
  {({ popperProps, restProps, scheduleUpdate }) =>
    <ResizeAware onResize={scheduleUpdate} onlyEvent style={{ position: 'relative' }}>
      <div>Some content here</div>
    </ResizeAware>
  }
</Popper>
```

**Comment by jamiewinder** [comment]
Thank you, I was unaware that this was passed into the render function!
