### ISSUE TITLE
react-popper undefined when bundled by rollup as an external and used in webpack app

### ISSUE THREAD

**Issue by lukaszczapiga** [souporserious/react-popper#66]
Hi,

I have a bundle created using rollup and react-popper is listed as an external of that bundle. Then that bundle is consumed by a webpack application as an ES bundle (to allow for better tree shaking).

At application runtime _reactPopper is undefined.

This problem goes away (as well as tree shaking) when using UMD bundle from rollup. 

Has anyone managed to configure rollup bundle with react-popper as an external and consume it as part of an ES bundle in webpack?

Thank you for any suggestions.

**Comment by julianljk** [comment]
I'm getting a similar issue! I'm using React-datepicker that has react-popper as a dependency, and it seems to be coming back undefined for me as well.

**Comment by souporserious** [comment]
Sorry about that! :/ I'm in the middle of a bunch of work right now, but please feel free to submit a PR and I will review and merge it if it looks good.

**Comment by souporserious** [comment]
@FezVrasta are you familiar with setting up bundled ES files? Not sure how to fix this one 😕

**Comment by FezVrasta** [comment]
I use Rollup to bundle ES stuff and it works just fine, but I'm sure webpack should work just fine as well.

**Comment by FezVrasta** [comment]
I'm quite sure this will get fixed with #109

**Comment by FezVrasta** [comment]
Should be fixed by 0.9.1
