### ISSUE TITLE
Major version with React 16 as primary React version?

### ISSUE THREAD

**Issue by FezVrasta** [souporserious/react-popper#69]
I was thinking that we may ship a breaking change as major version that switches the value of the `tag` of `Manager` to `false` by default.

This will make the library work with the new wrapless-components of React 16 but will still allow to fallback to the old behavior of a wrapping element if user is using an older version.

What's your take on this?

**Comment by souporserious** [comment]
I like it! I've been meaning to do this since the release of React 16. Only thing is I don't think it's in a `1.0.0` state yet. I think we may be able to clean up the way refs are handled by just using id's and I'd like to get tests written first. Can you bump it from `0.7.4` to `0.8.0`?

**Comment by FezVrasta** [comment]
I just hope to don't piss off to many people with the breaking change 😂

**Comment by FezVrasta** [comment]
Anyway, done!

https://github.com/souporserious/react-popper/pull/70

**Comment by FezVrasta** [comment]
Closing, I'm going to release a major version with React 16 as minimum supported version instead.
