### ISSUE TITLE
Custom component on Target makes Popper invisible

### ISSUE THREAD

**Issue by FezVrasta** [souporserious/react-popper#7]
```
import React from 'react';
import { Manager, Target, Popper } from 'react-popper';

const Div = props => <div {...props} />;

export default function Stuff() {
  return (
    <Manager>
      <Target component={Div}>
        Click me
      </Target>
      <Popper>
        <div>
          Something here
        </div>
      </Popper>
    </Manager>
  );
};
```

This renders a Popper element with `opacity: 0`.

Am I doing something wrong?

**Comment by FezVrasta** [comment]
So, reading the source code looks like `component` can only be one of the existing HTML tags managed by React...

It would be very useful if we could define custom components.

**Comment by souporserious** [comment]
Fixed https://github.com/souporserious/react-popper/commit/aa47f287eb9cf9f59d67df9d5c42eca771402f9b 🎉  I was using functional components so it wasn't finding the DOM node properly 😕
