### ISSUE TITLE
Odd behavior when popover is bigger than viewport

### ISSUE THREAD

**Issue by PlayMa256** [souporserious/react-popper#74]
Hello,
I'm having problems when the popover, placed at bottom, hits/gets bigger than the viewport. When it hits the viewport, it goes above the attached element.
You can see the baviour here:
https://codesandbox.io/s/r5yw8nv43q

I've tried to work with the `preventOverflow` and with the `keepTogether` properties, but no progress.

**Comment by FezVrasta** [comment]
That's the flip modifier

**Comment by PlayMa256** [comment]
Well, yeah =X
Thank you very much.

**Comment by FezVrasta** [comment]
You are welcome, the behavior is probably not the most intuitive, expect it to get better by default in the next major release of Popper.js
