### ISSUE TITLE
How to prevent wrapping of <Target>'s children

### ISSUE THREAD

**Issue by priyajeet** [souporserious/react-popper#79]
```
<Target>
  {Children.only(children)}
</Target>
```

renders
```
<div>
  <dom of my component>
</div>
```

The `div` wrapping causes issues because it has by default block style whereas the child can be an inline element or with its own padding/margins etc.

Desired output should just be `<dom of my component>` without wrapping divs.
Target should ideally be cloning `Children.only(children)`.

**Comment by TheSharpieOne** [comment]
You can use `Target`'s `component` prop to pass a component which it will render.
```jsx
<Target component={MyComponentWhichIsDynamic} />
```

**Comment by priyajeet** [comment]
Thanks, that works. Weirdly though, I tried that before posting this question, and it gave some ownerDocument error. I must have made a mistake. User error.

**Comment by priyajeet** [comment]
@TheSharpieOne I think I misspoke. I do get errors using that approach.

When I do

`<Target component={ cloneElement(Children.only(children), componentProps) } />`

I get:

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `Target`.

When I do

`<Target component={ Button  } />` where Button is a specific component, I get:

Warning: React does not recognize the `innerRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `innerref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by souporserious** [comment]
You might be able to use a [child function](https://github.com/souporserious/react-popper#usage-w-child-function) here. Maybe something like this:

```jsx
function MyPopper({ target, children }) {
  return (
  <Manager>
    <Target>
      {({ targetProps }) => (
        <div {...targetProps}>
          {target}
        </div>
      )}
    </Target>
    <Popper placement="left">
      {popperProps => cloneElement(Children.only(children), {...someOtherPropsIamMixingIn, ...popperProps})}
    </Popper>
  </Manager>
  )
}
```

**Comment by priyajeet** [comment]
@souporserious I guess I am not understanding it properly, the issue is the wrapping of the `{target}` which is passed in as a react element, and not the Popper's content.

Doing the following gives issues:

```js
<Target>
    {({ targetProps }) =>
        cloneElement(Children.only(children), {
            ...someOtherPropsIamMixingIn,
            ...targetProps
        })
    }
</Target>
```

My component's interface/usage is like this

```
<Tooltip text="some text">
    <Button ... />
</Tooltip>
```

where the `<Button ...>` is the target on which the "some text" tooltip should show. In your example above, assume `target` is a React element being passed in. Its still being wrapped in a <div> based on https://github.com/souporserious/react-popper/blob/master/src/Target.jsx#L5

Shouldn't Target.jsx be checking if the `children` is a react element (it already checks if its a function and if not it uses createElement), then its needs to use cloneElement instead of createElement?

**Comment by souporserious** [comment]
Ahh sorry, I forgot to mention that you need to pass the ref down properly. See more [here](https://github.com/souporserious/react-popper#children-proptypesoneoftypeproptypesnode-proptypesfunc).

So something like this (untested):

```jsx
function MyPopper({ target, children, ...restProps }) {
  return (
    <Manager>
      <Target>
         {({ targetProps }) => cloneElement(target, { innerRef: targetProps.ref })}
      </Target>
      <Popper placement="left">
        {popperProps =>
          cloneElement(Children.only(children), {
            ...restProps,
            ...popperProps,
            innerRef: popperProps.ref
          })}
      </Popper>
    </Manager>
  )
}

function Button({ innerRef, title, ...restProps }) {
  return (
    <button ref={innerRef} children={title} {...restProps} />
  )
}

function App() {
  return (
    <MyPopper
      target={<Button title="Trigger" />}
    >
      Popper
    </MyPopper>
  )
}
```

**Comment by priyajeet** [comment]
Thanks, that works, just that it forces modification of the child component. In other words, one will have to go modify any possible child element to accept and innerRef prop.

Are there any plans for future plans to rely more on ids/classes/querySelector/findDomNode, so that things works agnostic of the child component's structure?

**Comment by souporserious** [comment]
Yes, I've been thinking about just using a generated id and `getElementById` to get around the `ref` song and dance since it makes things a lot more complicated. I'm going to close this since it sounds like it's working, but I'll be sure to take this into consideration on the next major release.

**Comment by souporserious** [comment]
@priyajeet what about an API like this?

```
<Popper>
  {({ bindTarget, bindPopper }) => (
    <div>
      <div ref={bindTarget}>
        Target
      </div>
      <div ref={bindPopper({ modifiers: [], placement: 'left' })}>
        Popper
      </div>
    </div>
  )}
</Popper>
```

@FezVrasta this would solve the whole `Manager` issue 😁  and honestly cleanup a ton of this stuff.

**Comment by FezVrasta** [comment]
For sure it's cleaner, I like it.

**Comment by priyajeet** [comment]
Does look cleaner for sure, but still expects you to have a wrapping `<div>`  for the ref's since React wont allow refs on stateless components if Target is stateless. Also if the Target results in an inline or inline block element, then the popper will take incorrect positioning due to that div being a block. One could add an inline-block style on the div (which is what I am currently doing in my code base), or use another DOM node like span, but that again will have to be determined based on what the target ends up being, which generally falls out of the scope as its an incoming prop or child from the parent component and unknown to the component actually making the popup/tooltip. Also styling the div doesn't guarantee it will take the exact same space as its contents since the contents can have margins.

I think I liked the approach in react-tether, where iirc classes get added to the target and looked up using them?!? Not sure. Quite like the id approach you are talking about above too, lodash/uniqueid could just generate random ids and lookups  can be made using them.

**Comment by FezVrasta** [comment]
@priyajeet if you use React 16 you can avoid the wrapping `<div>`

**Comment by priyajeet** [comment]
Yeah React 16 helps there, but was wondering where the ref would go if a stateless Target component is passed down as children?

```
<div ref={bindTarget}>
    {children}
</div>
```

**Comment by FezVrasta** [comment]
that's a limitation of React, we usually make the stateless component accept a `getRef` property that proxies the ref:

```
function Stateless({ getRef }) {
  return <div ref={getRef} />
)
```

**Comment by souporserious** [comment]
I'm going to play with the `id` idea. I like that a `ref` allows me to know when the component has been unmounted because then I can destroy the popper and do cleanup work.
