### ISSUE TITLE
Request: Move popper.js dependency to peer-dependencies

### ISSUE THREAD

**Issue by k2snowman69** [souporserious/react-popper#82]
Just kicking around the idea here... this is a wrapper project that should be generally forward compatible with non-breaking changes. That said, it is slightly annoying whenever I need to test `popper.js@next` functionality or worse yet, if a breaking change came with popper.js, I'm stuck with whatever build react-popper is on due to the direct dependency.

My suggestion is to change it to a peer dependency. This allows people who want to use an alternate version of popper.js to use it.

**Comment by FezVrasta** [comment]
Why can't you just specify the version you want in your own package.json?

If you use Yarn you can also use the `resolutions` field

**Comment by k2snowman69** [comment]
Tried that... Looking at the dist output for react-popper (node_modules\react-popper\dist\react-popper.js) it seems that popper.js is included in the output of this package. So no matter what version I include in my package.json, it gets overwritten by the one included in this library (for the context of this library).

Unless I'm missing something here...

Repro steps:
1. npm install --save popper.js@next
Note: Currently 1.13 (trying to test positionFixed property)
2. npm install --save react-popper
3. In a component, import react-popper and use it
4. Use webpack to build
5. Check output and see if you can find positionFixed

Expected:
I should be able to find it in the output
Actual:
Not there

**Comment by FezVrasta** [comment]
Nope, this package doesn't embed the Popper.js library. You can specify the version you prefer.

**Comment by k2snowman69** [comment]
Line 2848 of https://unpkg.com/react-popper/dist/react-popper.js looks identical to https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/index.js

Are you sure you don't embed Popper.js in this library?

**Comment by FezVrasta** [comment]
Oh that's new, it wasn't like that in previous versions, something is wrong.

cc @souporserious

**Comment by k2snowman69** [comment]
Here is where I'm at so far with this:
Adding this to the webpack.prod.config.js does remove popper.js from the build output
```
const externals = {
  ...
  'popper.js': {
    root: 'PopperJS',
    commonjs2: 'popper.js',
    commonjs: 'popper.js',
    amd: 'popper.js',
  },
}

```

Which is a great first step! Now that it's no longer being built in, how to use your own popper.js version? Well sadly you're still screwed. The reason (I think) is because using node's module resolution, it's going to pick up the version in react-popper's module folder, not your app's node module folder. So even if you install popper.js@next (which is 1.13.0-next.1) what gets picked up is still 1.12.9.

Looking at Twitter's bootstrap, they include popper.js as a peer-dependency, probably for this exact scenario (using the version you want to use). That said after I moved popper.js to a peer dependency in react-popper, I couldn't quite figure out how to configure webpack to load my local version of popper.js. Instead I keep getting the error:
```
ERROR in D:/Temporary/react-popper/lib/react-popper.js
Module not found: Error: Can't resolve 'popper.js' in 'D:\Temporary\react-popper\lib'
```

Sadly, my project is in a bit of a mess state right now (adding new components, lots going on) so I can't really use it as an example. Anyway, hopefully all that information will be useful for whoever looks into it next. Seems like a big deal and I'll help where I can.

For now, I'm going to fork, up the version number and move forward. That said, I would love to get this working...

**Comment by k2snowman69** [comment]
Oh another change that will need to happen.
Popper.jsx line 110 - Need to pass positionFixed from props to PopperJS.

That said, I don't know why this code has default props defined in it because popper.js has the same default props defined. Seems like duplicate code that you should be able to delete and then just use a spread operator to fill the object being passed through.

**Comment by k2snowman69** [comment]
I created a branch to track some of these changes, you can cherry pick whatever you want and build your own change list.

https://github.com/k2snowman69/react-popper

**Comment by k2snowman69** [comment]
@souporserious any news? I'd love to use this library but would need popper.js 1.13 for the positionFixed fix.

**Comment by k2snowman69** [comment]
When no response... fork!
https://github.com/snowcoders/react-popper

**Comment by souporserious** [comment]
Sorry, just getting to this. If you have found a fix, please feel free to submit a PR and I will review it.

**Comment by jony89** [comment]
`popper-js` totally should be a peerDependecy, for two main reasons : 

1. testing, allow to easily mock `popper-js` (see https://github.com/FezVrasta/popper.js/issues/478 if u want to know why)
2. allow to have one instance of `popper-js` in the final bundle that is specified in the main project.

 I think this issue should be open

**Comment by FezVrasta** [comment]
@jony89 you can already mock Popper.js and make react-popper use the mock, it's done automatically once you add the Popper.js mock file.

Your package manager will automatically dedupe dependencies if the version range allows it.

**Comment by jony89** [comment]
Thats what I've done, but it forces me to have `popper.js` as my direct dependency (which is not, unless it will be a peerDependecy). 

Otherwise I'll be requiring a module that is not my direct dependency and relying on `react-popper` to install it on the top level of `node_modules`. That's not good.

**Comment by FezVrasta** [comment]
If you follow these steps you don't need any direct popper.js dependency.

https://github.com/FezVrasta/popper.js/issues/478#issuecomment-341506071

**Comment by jony89** [comment]
first line on the link you gave : 

`import PopperJs from 'popper.js';`

**Comment by FezVrasta** [comment]
Yes, but it's going to require the dependency of react-popper, that's the way npm and yarn work, they install all the dependencies in `node_modules` and they are then able to being required even if not explicitly set as dependency.

**Comment by jony89** [comment]
Hey, That's just what I wrote : 

> Otherwise I'll be requiring a module that is not my direct dependency and relying on react-popper to install it on the top level of node_modules. That's not good.

Don't tell me you think it's a good practice to require a module in your code that u are not explicit dependent on. :S

**Comment by FezVrasta** [comment]
Yes it's okay, because you want to mock a dependency of a dependency you rely on, there's nothing wrong with it.

I'm not going to make Popper.js a peerDependency, it doesn't make any sense, really.

**Comment by jony89** [comment]
I disagree. 

Anyway, there are more reasons why Popper.js should be a peerDependecy,

I can easily use some other tooltip or some other tool/lib that uses a different version of popper.js that is compatible with react-popper as well but eventually I'll get two versions of popper.js in my bundle. 

popper.js is a huge lib that can be used in many other libs.

**Comment by FezVrasta** [comment]
react-popper sets its popper.js version range to one that supports all the features and fixes needed by it to work. If you wanted to use an older version you'd encounter bugs.

Anyway, you can always use the `resolutions` property of `package.json` with Yarn to override an indirect dependency version if really needed, but you shouldn't.

Also, Popper.js is still under heavy development and every release usually ships with important fixes or features that anyone using the library should aim to have in their own code.

**Comment by jony89** [comment]
> Also, Popper.js is still under heavy development and every release usually ships with important fixes or features that anyone using the library should aim to have in their own code.

That's just support my claim that I should not rely on `react-popper` to ship new fix bugs. I know and I follow popper.js. so do others. react-popper is just a small wrapper around it.

IMO, you should treat popper.js the same u do with `react-dom` and `react`. all your claims can be said for this libs as well. but yet u have decided to have them as peerDependecy.

**Comment by FezVrasta** [comment]
Last reply on this matter, `react` and `react-dom` are marked as peerDependencies because they are supposed to be already used in your project for everything else, so it wouldn't make sense to set them as implicit dependencies, because that would mean that you would be forced to follow the requirements of this library to use React.

popper.js, on the other hand, is the set as implicit dependency because this library, as you said, is just a thin wrapper around it, so it needs to have fine control over its version to be able to work properly. Also, it's unlikely that you'll want to use popper.js directly if you are using react-popper, but that's not the reason behind the choice.

**Comment by jony89** [comment]
And my last comment as well : 

> it needs to have fine control over its version to be able to work properly.

That's exactly what peerDependency allows u to do :)
