### ISSUE TITLE
The hide modifier not working on Popper in a Portal on older versions of popper.js

### ISSUE THREAD

**Issue by greg-a-smith** [souporserious/react-popper#84]
I have a project that is using react-popper directly and indirectly (through react-datepicker) and it uses modals with scrolling regions.  I want to make use of the `hide` modifier (which is enabled by default in popper.js), but in popper.js versions prior to 1.12.7, this is not working correctly as the `data-x-out-of-boundaries` attribute is not being added when the target scrolls out of view and the Popper is in a Portal.  The core issue was fixed in popper.js version 1.12.7.

The issue I'm truly having is getting popper.js 1.12.7 (or higher) installed.  In my project, I have the react-popper dependency set to `^0.7.4` which has its popper.js dependency set to `^1.12.5`.  When I run `npm install` and then `npm ls popper.js`, I see it installs react-popper 0.7.4 with popper.js 1.12.6.  I'm not sure why it doesn't go to 1.12.9, but that may be an npm issue.

I created a pull request (#83) with updated examples that will show this "in action".  The third example is the new one I added.  It is a scrolling region with a target and a popper in it.  To show the hide modifier working and not working, I am able to replicate the behavior using two different package managers within react-popper (use the branch from pull request #83).  When I use npm, it installs popper.js 1.12.9 and **works**, but when I use yarn, it installs popper.js 1.12.5 and **doesn't work**.

Taking inconsistencies between npm and yarn out of the equation, could we just update the `package.json` file to set the popper.js dependency to `^1.12.9`?

**Comment by souporserious** [comment]
Can you try this out on the latest version please? I think the recent update I just published might have fixed this issue 🤞

**Comment by greg-a-smith** [comment]
@souporserious Yes, the 0.8.0 release addresses this issue.  Thank you!

Just a side note, although 0.8.0 is released (available on npmjs.com) and is documented in the change log, I don't see an 0.8.0 release or tag on GitHub.com.

**Comment by souporserious** [comment]
Oops forgot to tag the release! I'll do that today. Thanks for the reminder 😅glad that fixed things!
