### ISSUE TITLE
Manager export is failing 

### ISSUE THREAD

**Issue by laynef** [souporserious/react-popper#98]
I am using Reactstrap which uses this library and there seems to be an issue with this exported file.

~/node_modules/react-popper/lib/react-popper.js:1
 (function (exports, require, module, __filename, __dirname) { export { default as Manager } from './Manager';
                                                               ^^^^^^

 SyntaxError: Unexpected token export
     at createScript (vm.js:80:10)
     at Object.runInThisContext (vm.js:139:10)
     at Module._compile (module.js:599:28)
     at Object.Module._extensions..js (module.js:646:10)
     at Module.load (module.js:554:32)
     at tryModuleLoad (module.js:497:12)
     at Function.Module._load (module.js:489:3)
     at Module.require (module.js:579:17)
     at require (internal/module.js:11:18)
     at Object.defineProperty.value

**Comment by laynef** [comment]
I found the problem reactstrap needs to update their version of react-popper to the latest version so to fix this on your project just install the latest react-popper version on your project

**Comment by TheSharpieOne** [comment]
The latest version of react-popper doesn't work with rollup which is what reactstrap uses to create dist files for releases.
Basically, the last two versions of react-popper have had issues, a PR to fix the issues has been waiting to be merged for a while.

**Comment by NathanCH** [comment]
This problem has wacked my project up. I installed the latest version of Reactstrap, saw this error, downgraded back to my old version but I still get the error. Deleted package.json, /node_modules/. Even downgraded to earlier version of Reactstrap.

Funny that both Reactstrap and Bootstrap teams continually have issues with Popper and Tether.

**Comment by FezVrasta** [comment]
@TheSharpieOne what's the PR? And what's the problem with Rollup?

**Comment by TheSharpieOne** [comment]
There were a few of them as the probably kept coming back. #128 shows the code that was being generated. Basically rollup couldn't determine what was being exported due to how it transpiled the `export ... from '...'`.
Also #127 #93

**Comment by FezVrasta** [comment]
We don't use `export ... from '...'` in the current codebase 🤔

**Comment by TheSharpieOne** [comment]
Yeah, it's already been fixed, the last comment (before today) was from a while ago.

**Comment by FezVrasta** [comment]
Oh lol sorry
