### ISSUE TITLE
Popup outside viewport since 8.2.0

### ISSUE THREAD

**Issue by screendriver** [souporserious/react-popper#99]
With v0.7.5 it looks like this

<img width="447" alt="screen shot 2018-03-05 at 16 35 23" src="https://user-images.githubusercontent.com/149248/36983772-84a973f2-2093-11e8-849c-c7802c2f1bd6.png">

But with v0.8.2 it looks like this

<img width="260" alt="screen shot 2018-03-05 at 16 36 00" src="https://user-images.githubusercontent.com/149248/36983782-8d2986ca-2093-11e8-9e93-12a9d1e03146.png">

As you can see the dialog gets cut of and doesn't fit in the viewport anymore.

**Comment by FezVrasta** [comment]
Please open the issue on the Popper.js repository because it's most likely a regression of it. Make sure to fill out all the required fields during the issue creation.

**Comment by screendriver** [comment]
Ok. Thank you.
